docs
InseeFrLab/sugoi-api pull request #216
Opened 2021-03-19 11:00 UTC by micedre

Co-authored-by: Donatien Eneman <Donatien26@users.noreply.github.com>
Co-authored-by: Cécile Chemin <CChemin@users.noreply.github.com>
Signed-off-by: Cédric Couralet <cedric.couralet@insee.fr>

2021-04-01 12:01 UTC, micedre commented
Not a complete documentation, but I think it could be enough for a start.

2021-04-02 08:46 UTC, CChemin commented on docs/configuration.md
> +All configuration is done through spring properties. By default, spring Boot loads properties from application.properties. You can also use system properties for example ```java -jar app.jar -DNameof
```java -Dspring... instead of batch, my mistake sorry

2021-04-02 08:49 UTC, CChemin commented on docs/configuration.md
> +    - [Other info configuration](#other-info-configuration)
needs a blank line ?

2021-04-02 08:51 UTC, CChemin commented on docs/concepts.md
> +* do whatever the writer can do on all realms.
* instead of -

2021-04-02 08:52 UTC, CChemin commented on docs/concepts.md
> +The file is expected to contain an array of realm representations, like :
blank line

2021-04-02 08:53 UTC, CChemin commented on docs/concepts.md
> +
delete blank lines

2021-04-02 09:05 UTC, CChemin commented on docs/concepts.md
> +Each object is stored in a json file located in the folder located as configured in the realm.
in the folder as configured in the realm instead of located as configured in the realm ?

2021-04-02 09:07 UTC, micedre commented on docs/concepts.md
> +* do whatever the writer can do on all realms.
instead of ?

2021-04-02 09:10 UTC, micedre commented
@CChemin I tried to fix all your remarks, could you check ?

2021-04-02 10:02 UTC, CChemin requested changes

2021-04-02 10:31 UTC, micedre commented on sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/ApplicationService.java
> +   * Finds and app by some properties
I think we want all the groups, I modified the comment to indicate that, this could be fixed in ldap provider later.

2021-04-02 10:38 UTC, CChemin commented on sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/ApplicationService.java
> +   * Finds and app by some properties
all the groups with all the users ?

2021-04-02 10:42 UTC, micedre commented on sugoi-api-core/src/main/java/fr/insee/sugoi/core/service/ApplicationService.java
> +   * Finds and app by some properties
yes

2021-04-02 11:28 UTC, Donatien26 approved these changes

2021-04-02 11:33 UTC, merged