Resolve 215 - Add constant for realm config keys
InseeFrLab/sugoi-api pull request #238
Opened 2021-04-06 10:10 UTC by Donatien26

Signed-off-by: Donatien Eneman <donatien.eneman@insee.fr>

2021-04-06 11:24 UTC, CChemin commented on sugoi-api-core/src/main/java/fr/insee/sugoi/core/configuration/ConstantConfig.java
> +  public static final String ORGANIZATION_SOURCE = "organization_source";
why not using an enum ?

2021-04-06 11:26 UTC, CChemin commented on sugoi-api-core/src/main/java/fr/insee/sugoi/core/configuration/ConstantConfig.java
> +public class ConstantConfig {
I'd rather name it something more precise, maybe RealmConfigKey ?

2021-04-06 11:29 UTC, micedre requested changes

2021-04-06 11:29 UTC, micedre commented on sugoi-api-file-store-provider/src/main/java/fr/insee/sugoi/store/file/configuration/ConstantConfiguration.java
> +  public static final String ORGANIZATION_SOURCE = "organization_source";
Why not use the ones defined in  `sugoi-api-core/src/main/java/fr/insee/sugoi/core/configuration/ConstantConfig.java` ?

2021-04-06 11:29 UTC, micedre commented on sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/config/ConstantConfiguration.java
> +  public static final String TYPE = "TYPE";
Same comment as the FileProvider,some constants should be reused when possible. Also the classNameseems too generic, maybe `LdapConstants`

2021-04-06 14:42 UTC, Donatien26 commented
So we have A GlobalKeysConfiguration class where we can find commun key between all the config provider (jms, ldap, filter). We also have one class of keys configuration by provider (ldap, file,...) which extends the firstOne.

Moreover there is a GenericKeysConfig for keys not used by a provider and a EventKeysCOnfiguration for the keys use by the sugoi event part

2021-04-07 12:38 UTC, micedre approved these changes

2021-04-07 12:38 UTC, merged