[BUG] 🐛  Renew connection with ldap if server is down
InseeFrLab/sugoi-api pull request #392
Opened 2021-07-12 09:55 UTC by Donatien26

Signed-off-by: Donatien Eneman <donatien.eneman@insee.fr>

2021-07-16 13:43 UTC, CChemin commented on sugoi-api-ldap-store-provider/src/main/java/fr/insee/sugoi/store/ldap/LdapReaderStore.java
> +      throw new RuntimeException(e);
is this necessary ?

2021-07-19 05:18 UTC, micedre requested changes

2021-07-19 05:18 UTC, micedre commented on sugoi-api-ldap-utils/src/main/java/fr/insee/sugoi/ldap/utils/LdapFactory.java
> +  public static LDAPConnection getSingleConnection(Map<String, String> config, boolean force_erase)
Please avoid underscore in variable names

2021-07-21 11:08 UTC, micedre approved these changes

2021-07-21 11:08 UTC, merged